### ISSUE TITLE
Questions ?

### ISSUE THREAD

**Issue by shrkwy** [Eltik/AniSync#6]
Nice to see a mapping project for anime, currently am working on https://kimitsu.eu.org/ and looking forward to implement different mapping method.

I am interested in knowing how this works and if this depends on MalSync or works independently?

Also, how may I see a demo of this, is there an API made with this on the internet?

At last, how may I self host this this up on something like vercel if it's an API?

**Comment by shrkwy** [comment]
Oh! My bad. Guess I should've checked mapping.ts before for knowing how it works.

**Comment by Eltik** [comment]
Hey thanks for being interested in AniSync. You probably have already noticed but this project isn't dependent on MALSync or any other API's except for providers that require an API like MAL. If you want a demo, you can see my website Anify (https://anify.tv). If you want to self-host, I included an express server example in `/server/server.ts`.
